const Koa = require('koa')
const app = new Koa()
const cors = require('./utils/cors')
const router = require('./router')
const compress = require('koa-compress')
app.use(cors())
app.use(compress())
router(app)
app.listen(8082, () => {
  console.log('8082')
})
